// <auto-generated />
namespace LojaInformatica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Deltandocampodesenha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deltandocampodesenha));
        
        string IMigrationMetadata.Id
        {
            get { return "201809111355100_Deltando campo de senha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
